name: Run Pytest

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12

    - name: actions-pytest
  # You may pin to the exact commit or the version.
  # uses: xoviat/actions-pytest@6e27d0810b47a907cc45bc96092599f072b28870
      uses: xoviat/actions-pytest@0.1-alpha2
          
