name: Run Pytest

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      EMAIL_REFRESH: "false"

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.12 

    - name: Install Poetry
      run: |  
        python -m pip install --upgrade pip
        pip install poetry  # Installiere Poetry
        echo "$HOME/.local/bin" >> $GITHUB_PATH  # Stellt sicher, dass Poetry gefunden wird

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: .venv  # Speicherort der virtuellen Umgebung von Poetry
        key: ${{ runner.os }}-poetry-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          ${{ runner.os }}-poetry-

    - name: Install dependencies with Poetry
      run: |  
        poetry install --no-interaction  # Installiere alle Dependencies
      
    - name: Run tests
      run: poetry run pytest
          
